apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-vqcb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-vqcb
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-go-basic-vqcb
  namespace: dbruscin-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-vqcb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-vqcb
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:058e754a53e4e36299a2db05a1ec9ee4ef4bb624efdb6ec691f43e7f5226e450
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
